//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class abono
    {
        public Nullable<int> contrato { get; set; }
        public Nullable<int> @int { get; set; }
        public Nullable<decimal> prestamo { get; set; }
        public int indice { get; set; }
        public Nullable<decimal> abonado { get; set; }
    }
}
