//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class anterior_abono
    {
        public Nullable<int> cantidad { get; set; }
        public string descripcion { get; set; }
        public string subdescripcion { get; set; }
        public Nullable<decimal> valor_prenda { get; set; }
        public Nullable<decimal> prestamo { get; set; }
        public Nullable<int> registro { get; set; }
        public Nullable<int> folio_contrato { get; set; }
        public string origen { get; set; }
        public string caja { get; set; }
        public int no { get; set; }
    }
}
