//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartados_confg
    {
        public int no { get; set; }
        public string Nombre_plazo { get; set; }
        public Nullable<int> dias { get; set; }
        public Nullable<decimal> apartado_natural { get; set; }
        public Nullable<decimal> apartado_minimo { get; set; }
        public Nullable<int> dias_tolerancia { get; set; }
        public Nullable<int> dias_minimo { get; set; }
        public Nullable<decimal> penalizacion { get; set; }
        public Nullable<decimal> cancelacion { get; set; }
        public Nullable<int> ACTIVADO { get; set; }
    }
}
