//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartados
    {
        public int no { get; set; }
        public string FOLIO_REM { get; set; }
        public Nullable<int> bolsa { get; set; }
        public string noinv { get; set; }
        public string noserie { get; set; }
        public string descripcion { get; set; }
        public string detalles { get; set; }
        public Nullable<decimal> preciosugerido { get; set; }
        public Nullable<decimal> precioventa { get; set; }
        public string kilates { get; set; }
        public string peso_real { get; set; }
        public string condiciones { get; set; }
        public string tipo { get; set; }
        public string status { get; set; }
        public Nullable<double> apartado_con { get; set; }
        public Nullable<decimal> apartado_cantidad { get; set; }
        public string aparto { get; set; }
        public string idcliente { get; set; }
        public Nullable<decimal> resta_por_pagar { get; set; }
        public Nullable<System.DateTime> fecha_de_apartado { get; set; }
        public string usuario { get; set; }
        public string realizado_en { get; set; }
        public string comentario { get; set; }
        public Nullable<System.DateTime> liquido_fecha { get; set; }
        public string nota_liquido { get; set; }
        public Nullable<decimal> penalizado { get; set; }
        public Nullable<decimal> penalizado_precio { get; set; }
        public Nullable<System.DateTime> Fecha_de_penalizacion { get; set; }
        public string mot_penalizacion { get; set; }
        public string cancelo { get; set; }
        public Nullable<System.DateTime> fecha_cancelo { get; set; }
        public string mot_cancelo { get; set; }
        public string folio_apartado { get; set; }
        public string promocion { get; set; }
        public Nullable<System.DateTime> vigencia { get; set; }
        public Nullable<decimal> precio_origen { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public string tipo_desc { get; set; }
        public Nullable<decimal> precio_remate { get; set; }
        public Nullable<decimal> penalizacion_por { get; set; }
        public Nullable<decimal> cancelacion_por { get; set; }
        public Nullable<int> dias_minimo { get; set; }
        public Nullable<int> dias_normal { get; set; }
        public Nullable<int> dias_tolerancia { get; set; }
        public Nullable<decimal> apartado_min { get; set; }
        public Nullable<decimal> apartado_norm { get; set; }
        public string nombre_plazo { get; set; }
        public string tipo_apartado { get; set; }
    }
}
