//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int no { get; set; }
        public Nullable<int> Valor { get; set; }
        public string Concepto { get; set; }
        public string Procedimiento { get; set; }
        public string Area { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
    }
}
