//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditoria_resumen
    {
        public int no { get; set; }
        public Nullable<System.DateTime> fecha_reviso { get; set; }
        public string auditor { get; set; }
        public Nullable<double> calificacion { get; set; }
        public string jefe { get; set; }
        public string sucursal { get; set; }
        public string empresa { get; set; }
        public string sigla { get; set; }
    }
}
