//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditoria_fisica
    {
        public int no { get; set; }
        public Nullable<int> contrato { get; set; }
        public Nullable<decimal> prendas { get; set; }
        public string encontrado { get; set; }
        public string detalles { get; set; }
        public string tipo { get; set; }
        public string prendas_sistema { get; set; }
        public string status_contrato { get; set; }
        public Nullable<System.DateTime> fecha_contrato { get; set; }
        public string audito { get; set; }
        public string superviso { get; set; }
        public Nullable<System.DateTime> fecha_auditoria { get; set; }
        public string localidad { get; set; }
        public string diferencia { get; set; }
    }
}
