//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class autorizaciones_prestamos
    {
        public int no { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public string usuario { get; set; }
        public Nullable<decimal> anterior { get; set; }
        public Nullable<decimal> nuevo { get; set; }
        public string motivo { get; set; }
        public string paraelcontrato { get; set; }
    }
}
