//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class calificacion_aud
    {
        public int no { get; set; }
        public Nullable<int> indice { get; set; }
        public Nullable<int> calificacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> valor { get; set; }
        public string sucursal { get; set; }
        public string encargado { get; set; }
        public string sigla { get; set; }
        public string empresa { get; set; }
        public string audito { get; set; }
        public string detalles { get; set; }
        public string folio { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> valorobtenido { get; set; }
        public string proce { get; set; }
        public string concepto { get; set; }
        public Nullable<int> un { get; set; }
    }
}
