//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class clasificacion_cl
    {
        public int no { get; set; }
        public string Estatus_Considerados { get; set; }
        public string Preferencia { get; set; }
        public string activado { get; set; }
        public Nullable<System.DateTime> realizados_entre { get; set; }
        public Nullable<System.DateTime> realizados_entre2 { get; set; }
        public Nullable<decimal> Importes1 { get; set; }
        public Nullable<decimal> Importes2 { get; set; }
        public Nullable<decimal> Importes3 { get; set; }
        public Nullable<decimal> Importes4 { get; set; }
        public Nullable<decimal> Importes5 { get; set; }
        public Nullable<double> descuento1 { get; set; }
        public Nullable<double> descuento2 { get; set; }
        public Nullable<double> descuento3 { get; set; }
        public Nullable<double> descuento4 { get; set; }
        public Nullable<double> descuento5 { get; set; }
        public Nullable<decimal> cantidad1 { get; set; }
        public Nullable<decimal> cantidad2 { get; set; }
        public Nullable<decimal> cantidad3 { get; set; }
        public Nullable<decimal> cantidad4 { get; set; }
        public Nullable<decimal> cantidad5 { get; set; }
        public Nullable<System.DateTime> feccha { get; set; }
        public string realizo { get; set; }
        public string imagen1 { get; set; }
        public string imagen2 { get; set; }
        public string imagen3 { get; set; }
        public string imagen4 { get; set; }
        public string imagen5 { get; set; }
        public Nullable<int> dias { get; set; }
    }
}
