//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public string idClientes { get; set; }
        public string Nombre { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public string Colonia { get; set; }
        public string CP { get; set; }
        public string IFE { get; set; }
        public string Lada { get; set; }
        public string Tel { get; set; }
        public string Puntos { get; set; }
        public string Nombres { get; set; }
        public string noext { get; set; }
        public string noint { get; set; }
        public string estado { get; set; }
        public string ciudad { get; set; }
        public string pais { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public string sitio { get; set; }
        public string rfc { get; set; }
        public string contactoalt { get; set; }
        public string Apaterno { get; set; }
        public string Amaterno { get; set; }
        public string tipo { get; set; }
        public string altapor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int consec { get; set; }
        public string id1 { get; set; }
        public string id2 { get; set; }
        public Nullable<int> tipocliente { get; set; }
        public string nombre2 { get; set; }
        public Nullable<decimal> puntos_cliente { get; set; }
        public Nullable<decimal> PUNTOS_USADOS { get; set; }
        public Nullable<int> puntos_aumento { get; set; }
        public Nullable<int> puntos_interes { get; set; }
        public Nullable<int> puntos_venta { get; set; }
    }
}
