//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLONB
    {
        public Nullable<int> Folio { get; set; }
        public Nullable<int> Contrato { get; set; }
        public string Fecha { get; set; }
        public Nullable<int> Bolsa { get; set; }
        public Nullable<int> IdClientes { get; set; }
        public string NCliente { get; set; }
        public string AutorizoA { get; set; }
        public string Plazo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> FechaDesemp { get; set; }
        public string Comentario { get; set; }
        public string Dias { get; set; }
        public Nullable<System.DateTime> FechaCons { get; set; }
        public Nullable<decimal> Prestamo { get; set; }
        public Nullable<double> Interes { get; set; }
        public Nullable<double> seguro { get; set; }
        public Nullable<double> almacenaje { get; set; }
        public string plazo1 { get; set; }
        public string plazo2 { get; set; }
        public string plazo3 { get; set; }
        public Nullable<decimal> avaluo { get; set; }
        public string valuacion_tipo { get; set; }
        public string cancelado { get; set; }
        public string comentariocancelado { get; set; }
        public Nullable<decimal> prestamoprom { get; set; }
        public string origen { get; set; }
        public string folioavaluo { get; set; }
        public Nullable<int> clasificacion { get; set; }
        public string santerior { get; set; }
        public string caja { get; set; }
        public string pension { get; set; }
        public string Rev { get; set; }
        public int reg { get; set; }
        public Nullable<double> temp { get; set; }
        public string VenOVig { get; set; }
        public string realizo { get; set; }
        public Nullable<decimal> cobroOriginal { get; set; }
        public string BLOQUEADO_COMENTARIO { get; set; }
    }
}
