//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprobaciones
    {
        public int comprobacion_no { get; set; }
        public Nullable<System.DateTime> fecha_comprobacion { get; set; }
        public string codigo_comprobacion { get; set; }
        public string empresa { get; set; }
        public string suc { get; set; }
        public string dir { get; set; }
        public string responsable { get; set; }
        public string superviso { get; set; }
    }
}
