//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprobaciones_gastos
    {
        public int no { get; set; }
        public string caja { get; set; }
        public string tipo { get; set; }
        public string comprobante { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string comentario { get; set; }
        public string poliza { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string gasto { get; set; }
        public Nullable<System.DateTime> fechag { get; set; }
    }
}
