//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_valores_plazos
    {
        public int no { get; set; }
        public string nombre_calendario { get; set; }
        public string valor_en_cantidad { get; set; }
        public string sigla_asignada { get; set; }
        public string variable { get; set; }
    }
}
