//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class contabilidad
    {
        public int no { get; set; }
        public string Nombre { get; set; }
        public string Localidad { get; set; }
        public string Caja { get; set; }
        public string Clave { get; set; }
        public string Cuenta_prestamos { get; set; }
        public string Cuenta_caja { get; set; }
        public string Cuenta_interes { get; set; }
        public string Cuenta_iva { get; set; }
        public string departamento { get; set; }
        public string leyenda1 { get; set; }
        public string leyenda2 { get; set; }
        public string leyenda3 { get; set; }
    }
}
