//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_temporal
    {
        public Nullable<int> No { get; set; }
        public string Primer_plazo { get; set; }
        public Nullable<System.DateTime> Fecha_de_pago { get; set; }
        public Nullable<decimal> monto_prestamo { get; set; }
        public Nullable<decimal> Interes { get; set; }
        public Nullable<decimal> Seguro { get; set; }
        public Nullable<decimal> Almacenaje { get; set; }
        public Nullable<decimal> Total_a_pagar { get; set; }
        public Nullable<decimal> Refrendo { get; set; }
        public Nullable<int> Fecha_sistema { get; set; }
        public string contrato { get; set; }
        public string caja { get; set; }
        public Nullable<System.DateTime> fecha_compara { get; set; }
        public int indice { get; set; }
    }
}
