//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class descuentos_distintos
    {
        public int no { get; set; }
        public string folio { get; set; }
        public Nullable<int> contrato { get; set; }
        public Nullable<int> bolsa { get; set; }
        public string idcliente { get; set; }
        public string R_D { get; set; }
        public string tipo_C { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Status_contrato { get; set; }
        public string tipo_desc { get; set; }
        public Nullable<double> descuento { get; set; }
        public string comentario { get; set; }
        public Nullable<decimal> A_desempeñar { get; set; }
        public Nullable<decimal> D_desempeñar { get; set; }
        public Nullable<decimal> A_refrendar { get; set; }
        public Nullable<decimal> D_refrendar { get; set; }
        public Nullable<decimal> antes_prestamo { get; set; }
        public Nullable<decimal> ahora_prestamo { get; set; }
        public Nullable<decimal> antes_pension { get; set; }
        public Nullable<decimal> ahora_pension { get; set; }
        public Nullable<decimal> antes_resmision { get; set; }
        public Nullable<decimal> ahora_remision { get; set; }
        public string autorizo { get; set; }
        public string caja { get; set; }
        public string status { get; set; }
    }
}
