//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int Consecutivo { get; set; }
        public string NoEmpleado { get; set; }
        public string Nombre_Completo { get; set; }
        public string Nombres { get; set; }
        public string Apaterno { get; set; }
        public string Amaterno { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string No_int { get; set; }
        public string No_ext { get; set; }
        public Nullable<int> Cp { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string Sexo { get; set; }
        public string Edo_civil { get; set; }
        public Nullable<System.DateTime> Fecha_de_Nacimiento { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string No_Seguro_Social { get; set; }
        public string Nacionalidad { get; set; }
        public string Puesto { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public string Lugar_de_nacimiento { get; set; }
        public string Teléfono { get; set; }
        public string CEL { get; set; }
        public Nullable<System.DateTime> Fecha_de_Ingreso { get; set; }
        public string Localidad { get; set; }
        public string BAJA { get; set; }
        public string HORARIO_de { get; set; }
        public string HORARIO_a { get; set; }
        public string HORARIO_AM { get; set; }
        public string HORARIO_PM { get; set; }
        public string empresa { get; set; }
        public string ife { get; set; }
        public string estadocivil { get; set; }
        public string esposa { get; set; }
        public string hijos { get; set; }
        public string grado_estudios { get; set; }
        public string estudios_espcf { get; set; }
        public string fotografia { get; set; }
        public string altapor { get; set; }
        public Nullable<System.DateTime> fechaalta { get; set; }
        public string correo { get; set; }
        public string departamento { get; set; }
    }
}
