//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        public string NoControl { get; set; }
        public string Empresa { get; set; }
        public string Giro { get; set; }
        public string RFC { get; set; }
        public string Marca { get; set; }
        public string Calle { get; set; }
        public string noext { get; set; }
        public string noint { get; set; }
        public string cp { get; set; }
        public string colonia { get; set; }
        public string estado { get; set; }
        public string ciudad { get; set; }
        public string pais { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string paginaweb { get; set; }
        public string seguro { get; set; }
        public string poliza { get; set; }
        public string logotipo { get; set; }
        public string representadopor { get; set; }
        public string nofolioinicial { get; set; }
        public string nofoliofinal { get; set; }
        public string noaprobacion { get; set; }
        public string vigenciade { get; set; }
        public string vigenciafinal { get; set; }
        public string serie { get; set; }
        public string cbb { get; set; }
        public string altapor { get; set; }
        public Nullable<System.DateTime> fechaalta { get; set; }
        public int consec { get; set; }
    }
}
