//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadosRepublica
    {
        public int no { get; set; }
        public string Estado { get; set; }
        public string clave { get; set; }
        public string nom { get; set; }
        public Nullable<int> nom2 { get; set; }
    }
}
