//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETQ_VENTA
    {
        public int no { get; set; }
        public string Descripcion { get; set; }
        public string Detalles { get; set; }
        public string kt { get; set; }
        public string Peso { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string tipo { get; set; }
        public string Inventario { get; set; }
        public Nullable<decimal> especial { get; set; }
        public string pr { get; set; }
        public Nullable<decimal> REMATE_UNO { get; set; }
        public Nullable<decimal> REMATE_DOS { get; set; }
        public Nullable<decimal> REMATE_TRES { get; set; }
    }
}
