//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactCO
    {
        public Nullable<double> oro_24 { get; set; }
        public Nullable<double> oro_22 { get; set; }
        public Nullable<double> oro_18 { get; set; }
        public Nullable<double> oro_14 { get; set; }
        public Nullable<double> oro_12 { get; set; }
        public Nullable<double> oro_10 { get; set; }
        public Nullable<double> oro_8 { get; set; }
        public Nullable<decimal> valor_24 { get; set; }
        public Nullable<decimal> valor_22 { get; set; }
        public Nullable<decimal> valor_18 { get; set; }
        public Nullable<decimal> valor_14 { get; set; }
        public Nullable<decimal> valor_12 { get; set; }
        public Nullable<decimal> valor_10 { get; set; }
        public Nullable<decimal> valor_8 { get; set; }
        public int indice { get; set; }
        public Nullable<double> per1 { get; set; }
        public Nullable<double> per2 { get; set; }
        public Nullable<double> per3 { get; set; }
        public Nullable<double> per4 { get; set; }
        public Nullable<double> per5 { get; set; }
        public Nullable<double> per6 { get; set; }
        public Nullable<double> per7 { get; set; }
    }
}
