//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturas
    {
        public string Factura { get; set; }
        public Nullable<System.DateTime> FechaFact { get; set; }
        public string HoraFact { get; set; }
        public Nullable<int> Contrato { get; set; }
        public Nullable<int> Bolsa { get; set; }
        public Nullable<int> Folio { get; set; }
        public string DescripcionFact { get; set; }
        public Nullable<decimal> ImporteFact { get; set; }
        public Nullable<decimal> IVAFact { get; set; }
        public Nullable<decimal> TotalFact { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string Comentario { get; set; }
        public Nullable<decimal> Abono { get; set; }
        public string R_D { get; set; }
        public int NO { get; set; }
        public string caja { get; set; }
        public Nullable<decimal> Gastos_Operacion { get; set; }
        public Nullable<decimal> gastos { get; set; }
        public Nullable<decimal> descuento_gastos_op { get; set; }
        public Nullable<decimal> total_gastos_op { get; set; }
        public string leyendas { get; set; }
        public string leyenda2 { get; set; }
        public string leyenda3 { get; set; }
        public string STATUS { get; set; }
        public string origen { get; set; }
        public string cliente_Promocion { get; set; }
        public string Nota { get; set; }
        public Nullable<decimal> antes_refrendo { get; set; }
        public Nullable<decimal> ahora_refrendo { get; set; }
        public Nullable<decimal> antes_desempeño { get; set; }
        public Nullable<decimal> ahora_desempeño { get; set; }
        public Nullable<double> descuento_preferente { get; set; }
        public string leyendag { get; set; }
        public string leyendadescg { get; set; }
        public string leyendatotalg { get; set; }
        public string leyendaA { get; set; }
        public string plazo { get; set; }
        public Nullable<decimal> interes_N { get; set; }
        public Nullable<decimal> interes_A { get; set; }
        public string realizo { get; set; }
    }
}
