//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class fechasAU
    {
        public Nullable<System.DateTime> f1 { get; set; }
        public Nullable<System.DateTime> f2 { get; set; }
        public int @int { get; set; }
    }
}
