//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFS
    {
        public string localidad { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> prestamos_n { get; set; }
        public Nullable<decimal> prestamos_r { get; set; }
        public Nullable<int> cantidad_n { get; set; }
        public Nullable<int> cantidad_ref { get; set; }
        public Nullable<decimal> n_pago_d { get; set; }
        public Nullable<decimal> n_pago_r { get; set; }
        public Nullable<int> cantidad_d { get; set; }
        public Nullable<int> cantidad_r { get; set; }
        public Nullable<decimal> rem_v { get; set; }
        public Nullable<int> cantidad_v { get; set; }
        public Nullable<decimal> depositos { get; set; }
        public Nullable<decimal> retiros { get; set; }
        public Nullable<int> dep_cantidad { get; set; }
        public Nullable<int> ret_cantidad { get; set; }
        public Nullable<decimal> obsequio { get; set; }
        public Nullable<int> cantidad_obs { get; set; }
        public Nullable<decimal> saldo_caja_in { get; set; }
        public Nullable<decimal> saldo_caja_fin { get; set; }
        public string caja_loc { get; set; }
        public string usuario_cj { get; set; }
        public Nullable<decimal> cancel_p { get; set; }
        public Nullable<int> cantidad_p_c { get; set; }
        public Nullable<decimal> cancel_np { get; set; }
        public Nullable<int> cantidad_np_c { get; set; }
        public Nullable<decimal> cancel_rem { get; set; }
        public Nullable<int> cantidad_r_c { get; set; }
        public Nullable<decimal> p_autos { get; set; }
        public Nullable<int> c_autos { get; set; }
        public Nullable<decimal> p_joyeria { get; set; }
        public Nullable<int> c_joyeria { get; set; }
        public Nullable<decimal> p_elect { get; set; }
        public Nullable<int> c_elect { get; set; }
        public Nullable<decimal> p_otr { get; set; }
        public Nullable<int> c_otr { get; set; }
        public Nullable<decimal> abono { get; set; }
        public Nullable<int> c_abono { get; set; }
        public Nullable<int> total_trans { get; set; }
        public int id { get; set; }
        public Nullable<decimal> reimp { get; set; }
        public Nullable<int> cimp { get; set; }
    }
}
