//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class interes
    {
        public int no { get; set; }
        public Nullable<decimal> interes1 { get; set; }
        public Nullable<decimal> seguro { get; set; }
        public Nullable<decimal> almacenaje { get; set; }
        public string contrato { get; set; }
        public string caja { get; set; }
    }
}
