//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRG12
    {
        public int mov { get; set; }
        public string Caja { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public string Concepto { get; set; }
        public string Folio { get; set; }
        public Nullable<int> Contrato { get; set; }
        public Nullable<decimal> Debe { get; set; }
        public Nullable<decimal> Haber { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string Usuario { get; set; }
        public string Movim { get; set; }
        public string Status { get; set; }
        public string Comentario { get; set; }
    }
}
