//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocioncaja
    {
        public int no { get; set; }
        public string regalo { get; set; }
        public string concepto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> promocion { get; set; }
        public string realizo { get; set; }
        public string caja { get; set; }
        public string sucursal { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<decimal> valor_prenda { get; set; }
        public string entregado_a { get; set; }
        public string noserie { get; set; }
        public string NO_INV { get; set; }
    }
}
