//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class prom_aplica
    {
        public int ind { get; set; }
        public Nullable<int> por_cada_pt { get; set; }
        public Nullable<decimal> vale_tipo { get; set; }
        public string tipo { get; set; }
        public string operacion { get; set; }
        public Nullable<System.DateTime> vigencia { get; set; }
        public string activado { get; set; }
    }
}
