//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class promociones_Activas
    {
        public string promociones { get; set; }
        public string activa { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> descuento_porciento { get; set; }
        public Nullable<decimal> descuento_cantidad { get; set; }
        public Nullable<System.DateTime> VIGENCIA { get; set; }
        public string tipo { get; set; }
        public string operacion { get; set; }
        public string tipo_desc { get; set; }
        public Nullable<decimal> compra_mayor_a { get; set; }
        public string DOCUMENTO_REQUERIDO { get; set; }
        public Nullable<int> requeridas { get; set; }
        public Nullable<int> cobrar { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string realizo { get; set; }
        public int @int { get; set; }
    }
}
