//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class promociones
    {
        public int no { get; set; }
        public string folio { get; set; }
        public string concepto { get; set; }
        public Nullable<double> descuento { get; set; }
        public Nullable<decimal> anterior { get; set; }
        public Nullable<decimal> nuevo { get; set; }
        public string inv { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string realizo { get; set; }
        public string clave { get; set; }
        public string caja { get; set; }
        public string suc { get; set; }
    }
}
