//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocionesregalo
    {
        public int no { get; set; }
        public string nombre { get; set; }
        public string activa { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> vigencia_i { get; set; }
        public Nullable<System.DateTime> vigenci_f { get; set; }
    }
}
