//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRVyusuarios
    {
        public int no { get; set; }
        public string TIPO_USUARIO { get; set; }
        public string NO_OPERADOR { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASEÑA { get; set; }
        public string OPERACIONES { get; set; }
        public string SISTEMAS { get; set; }
        public string CAJAS { get; set; }
        public string AUDITORIA { get; set; }
        public string CONTABILIDAD { get; set; }
        public string ADMINISTRACION { get; set; }
        public Nullable<System.DateTime> FECHAALTA { get; set; }
        public string ALTAPOR { get; set; }
        public string LOCALIDAD { get; set; }
        public string BLOQUEADO { get; set; }
        public string FECHABLOQUEO { get; set; }
        public string HORABLOQUEO { get; set; }
        public string CAJA { get; set; }
        public Nullable<int> DIAS { get; set; }
        public Nullable<System.DateTime> FECHA_CAMBIO { get; set; }
    }
}
