//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class puntos_confg
    {
        public int no { get; set; }
        public string documento { get; set; }
        public string status_contratos { get; set; }
        public string status_NP { get; set; }
        public Nullable<decimal> cantidad_C { get; set; }
        public Nullable<decimal> cantidad_NP { get; set; }
        public Nullable<decimal> valor_pts_C { get; set; }
        public Nullable<decimal> valor_pts_NP { get; set; }
        public Nullable<System.DateTime> vigencia_de { get; set; }
        public Nullable<System.DateTime> vigencia_a { get; set; }
        public string activado { get; set; }
        public string echo_por { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
