//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reimpresiones
    {
        public int no { get; set; }
        public string reimpresion { get; set; }
        public Nullable<decimal> costo { get; set; }
        public string folio_reimpreso { get; set; }
        public string folio_nuevo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string caja { get; set; }
        public string cliente { get; set; }
        public string id_cliente { get; set; }
        public string realizo { get; set; }
    }
}
