//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retiros
    {
        public Nullable<int> no { get; set; }
        public string caja { get; set; }
        public string numcaja { get; set; }
        public string pertenecea { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string concepto { get; set; }
        public string descripcion { get; set; }
        public string estatus { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public string autorizo { get; set; }
        public string usuario { get; set; }
        public string nooperador { get; set; }
        public int comprobacionno { get; set; }
        public Nullable<System.DateTime> fecha_compro { get; set; }
        public string motivo { get; set; }
        public string responsable_fondo { get; set; }
        public string responsable_revisa { get; set; }
        public string codigo_compro { get; set; }
        public string documento_tipo { get; set; }
        public string no_doc { get; set; }
        public string folio { get; set; }
    }
}
