//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class selcaja
    {
        public string Caja { get; set; }
        public string Status { get; set; }
        public string NumCaja { get; set; }
        public string UltimoCont { get; set; }
        public string UltimoBolsa { get; set; }
        public string CajaAbrev { get; set; }
        public string ultfolio { get; set; }
        public string pertenecea { get; set; }
        public string altapor { get; set; }
        public string fechaalta { get; set; }
        public int Consec { get; set; }
        public string sucursal { get; set; }
        public string foliosNP { get; set; }
        public string impresora { get; set; }
        public Nullable<int> ocupada { get; set; }
        public string folio_apartado { get; set; }
        public string opcion_color { get; set; }
        public string opcion_font { get; set; }
        public string FOLIONP { get; set; }
        public string FOLIONR { get; set; }
    }
}
