//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_AVALUO
    {
        public string Cantidad { get; set; }
        public string Descripcion { get; set; }
        public string Subdescripcion { get; set; }
        public string Condiciones { get; set; }
        public string Kt { get; set; }
        public string P_Neto { get; set; }
        public string P_Real { get; set; }
        public Nullable<decimal> Valor_prenda { get; set; }
        public string Penalizado_con { get; set; }
        public string Plazo { get; set; }
        public Nullable<decimal> Prestamo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string alta_por { get; set; }
        public string folio { get; set; }
        public int no { get; set; }
        public Nullable<decimal> A { get; set; }
        public Nullable<decimal> B { get; set; }
        public string tipo { get; set; }
    }
}
