//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPavaluos
    {
        public int no { get; set; }
        public string definicion { get; set; }
        public string descripcion { get; set; }
        public string logo { get; set; }
        public string Su_avaluo_sera { get; set; }
        public string alta { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<int> premate { get; set; }
        public Nullable<decimal> desc_primero { get; set; }
        public Nullable<int> sremate { get; set; }
        public Nullable<decimal> desc_segundo { get; set; }
        public Nullable<int> remate { get; set; }
        public Nullable<decimal> limite_precio { get; set; }
        public Nullable<int> limite_refrendo { get; set; }
    }
}
