//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferencias
    {
        public int no { get; set; }
        public string envia { get; set; }
        public string no_suc { get; set; }
        public string remitente { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string sucursal { get; set; }
        public string correo { get; set; }
        public string empresa { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public string hora { get; set; }
        public string noserieC { get; set; }
        public string no_suc2 { get; set; }
        public string destinatario { get; set; }
        public string telefono2 { get; set; }
        public string direccion2 { get; set; }
        public string sucursal2 { get; set; }
        public string empresa2 { get; set; }
        public string correo2 { get; set; }
        public string transporta { get; set; }
        public string autoriza { get; set; }
        public string comentarios { get; set; }
        public string status_TRF { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public string condicones_entrega { get; set; }
        public string notificado_remitente { get; set; }
        public string suc_recibe { get; set; }
        public string quien_recibe { get; set; }
        public Nullable<System.DateTime> cerro_fecha { get; set; }
        public string codigo_recibo { get; set; }
        public string observaciones { get; set; }
    }
}
