//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALOR_FACTORES
    {
        public int No_Factor { get; set; }
        public string Nombre_Factor { get; set; }
        public string Porcentaje_a_considerar { get; set; }
        public string Estatus_del_Factor { get; set; }
        public string Factor_24_kt { get; set; }
        public string Factor_22_kt { get; set; }
        public string Factor_18_kt { get; set; }
        public string Factor_14_kt { get; set; }
        public string Factor_12_kt { get; set; }
        public string Factor_10_kt { get; set; }
        public string Factor_8_kt { get; set; }
        public string Comentario_adicional { get; set; }
        public string Alta_por { get; set; }
        public Nullable<System.DateTime> Fecha_alta { get; set; }
        public string p1 { get; set; }
        public string p2 { get; set; }
        public string p3 { get; set; }
        public string p4 { get; set; }
        public string p5 { get; set; }
        public string p6 { get; set; }
        public string p7 { get; set; }
        public string ad1 { get; set; }
        public string ad2 { get; set; }
        public string ad3 { get; set; }
        public string ad4 { get; set; }
        public string ad5 { get; set; }
        public string ad6 { get; set; }
        public string ad7 { get; set; }
    }
}
