//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALOR_FACTORES_MAS
    {
        public int No_Factor { get; set; }
        public string Nombre_Factor { get; set; }
        public string Porcentaje_a_considerar { get; set; }
        public string Estatus_del_Factor { get; set; }
    }
}
