//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKReportsemp.WinForms.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vencidos
    {
        public Nullable<int> Contrato { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Bolsa { get; set; }
        public string Descripcion { get; set; }
        public string SubDescripcion { get; set; }
        public string Kilates { get; set; }
        public string PesoReal { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Avaluo { get; set; }
        public Nullable<decimal> Prestamo { get; set; }
        public string EstatusPrenda { get; set; }
        public string Cantidad { get; set; }
        public string Localidad { get; set; }
        public string Ubicacion { get; set; }
        public string Posicion { get; set; }
        public string registro { get; set; }
        public string folio { get; set; }
        public string origen { get; set; }
        public int INT { get; set; }
        public string condiciones { get; set; }
        public Nullable<int> indice { get; set; }
        public string descripcion_ant { get; set; }
        public string subdescripcion_ant { get; set; }
        public string kilate_ant { get; set; }
        public string peso_ant { get; set; }
        public Nullable<decimal> prestamo_ant { get; set; }
        public Nullable<decimal> avaluo_ant { get; set; }
        public string tipo_ant { get; set; }
        public string condiciones_ant { get; set; }
        public string peso_neto_ant { get; set; }
        public string no_inventario { get; set; }
        public string no_serie { get; set; }
        public Nullable<decimal> Precio_venta { get; set; }
        public Nullable<decimal> Precio_remate { get; set; }
        public string no_control_v { get; set; }
        public Nullable<System.DateTime> fecha_control { get; set; }
        public string mod_agre { get; set; }
        public string Pneto { get; set; }
        public string caja { get; set; }
        public string cambio { get; set; }
        public string notas { get; set; }
        public string ESPECIFICOS { get; set; }
        public string STATUS_CONTRATO { get; set; }
        public string DETALLES_CONTRATO { get; set; }
    }
}
